openapi: 3.0.3
info:
  title: Contact API
  version: 1.0.0
paths:
  /v1/contacts:
    post:
      tags:
        - Contacts V1
      summary: Create a new contact
      operationId: createContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContactRequest'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateContactResponse'
          description: Contact created successfully
    get:
      tags:
        - Contacts V1
      summary: Get all contacts
      operationId: getContacts
      responses:
        '200':
          description: Get all contacts
          content:
            application/json:
              schema:
                type: array
                default: []
                items:
                  $ref: '#/components/schemas/Contact'

components:
  schemas:
    CreateContactRequest:
      allOf:
        - $ref: '#/components/schemas/Contact'

    CreateContactResponse:
      allOf:
        - $ref: '#/components/schemas/Contact'

    Contact:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        name:
          $ref: '#/components/schemas/Name'
        contactNumbers:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ContactNumber'
    Name:
      type: object
      properties:
        first:
          type: string
          example: 'Juan'
        last:
          type: string
          example: 'dela Cruz'
        suffix:
          type: string
          example: 'Jr.'
    ContactNumber:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        countryCode:
          type: string
          example: '+63'
        areaCode:
          type: string
          example: '917'
        subscriberNumber:
          type: string
          example: '123456'
        label:
          type: string
          example: 'Mobile'